web:
  image: nginx
  volumes:
   #- ./templates:/etc/nginx/templates
   #- ./conf/nginx.conf:/etc/nginx/nginx.conf
   - ./certificates/:/etc/nginx/certificates/
   - ./sites-available:/etc/nginx/sites-available/proxy.conf
  ports:
   - "8080:80"
  environment:
   - NGINX_HOST=foobar.com
   - NGINX_PORT=80
